server:
  port: 8090

spring:
  application:
    name: sharding-jdbc-demo
  # 配置真实数据源
  shardingsphere:
    datasource:
      names: ds-master-0,ds-master-1
      # 配置第1个数据源
      ds-master-0:
        # 数据库连接池类名称
        type: com.alibaba.druid.pool.DruidDataSource
        # 数据库驱动类名
        driver-class-name: com.mysql.jdbc.Driver
        # 数据库url连接
        url: jdbc:mysql://127.0.0.1:3306/sharding_m0?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
        #数据库用户名
        username: root
        # 数据库密码
        password: root
      # 配置第2个数据源
      ds-master-1:
        # 数据库连接池类名称
        type: com.alibaba.druid.pool.DruidDataSource
        # 数据库驱动类名
        driver-class-name: com.mysql.jdbc.Driver
        # 数据库url连接
        url: jdbc:mysql://127.0.0.1:3306/sharding_m1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
        #数据库用户名
        username: root
        # 数据库密码
        password: root
    # 配置 user 表规则
    sharding:
      tables:
        test_user:
          actual-data-nodes: ds-master-$->{0..1}.test_user_$->{0..1}
          # 配置分表策略 主键取模 0在0表 1在1表
          table-strategy:
            inline:
              #分片列名称
              sharding-column: id
              #分片算法行表达式
              algorithm-expression: test_user_$->{id % 2}
          # 主键策略 雪花算法 todo:此处生成的 id 有问题
#          key-generator:
#            column: id
#            type: SNOWFLAKE
      # 配置分库策略 主键取模0在0库 1在1库
      default-database-strategy:
        inline:
          sharding-column: id
          #分片算法行表达式
          algorithm-expression: ds-master-$->{id % 2}
    # 打开sql控制台输出日志
    props:
      sql:
        show: true

  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  type-aliases-package: com.kevin.springbootuse.shardingjdbc.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    banner: false

